### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by f-s**
5% quantile example

### CODE REVIEW

**Comment by RobTillaart** [comment]
OK straightforward,
Can you update the header of the example to match reality?

**Comment by RobTillaart** [comment]
I notice that 
```cpp
 float RunningMedian::getQuantile(float q) ```

does not check the range of q (between 0 and 1)

Should be fixed too I guess to prevent "strange" results

**Comment by f-s** [comment]
ok, i will do another merge request

**Comment by f-s** [comment]
Done that

**Comment by RobTillaart** [comment]
Thanks, looking good

**Pull request merged**
