### PR TITLE
Changes as requested

### PR DESCRIPTION
**Pull request by dralois**

### CODE REVIEW

**Comment by RobTillaart** [comment]
Sorry closed the other PR by mistake.

**Comment by RobTillaart** [comment]
Follow up of #15

**Comment by RobTillaart** [comment]
Looks good!

**Review by RobTillaart — APPROVED** [review]

**Comment by dralois** [comment]
> Sorry closed the other PR by mistake.

No worries, I figured 😄

**Comment by RobTillaart** [comment]
Had to bump the version to 0.3.6 as I got a publish problem on Platformio.
Anyway thanks again for your additions.

**Pull request merged**
